default.xml: Update poky to fix sdk build
sdk build would error out otherwise:

Setting up nativesdk-automake (1.16.2-r0) ...
dpkg: nativesdk-qemu-helper: dependency problems, but configuring anyway as you requested:
 nativesdk-qemu-helper depends on nativesdk-qemu.

Setting up nativesdk-qemu-helper (1.0-r9) ...
dpkg: nativesdk-packagegroup-sdk-host: dependency problems, but configuring anyway as you requested:
 nativesdk-packagegroup-sdk-host depends on nativesdk-qemu.
 nativesdk-packagegroup-sdk-host depends on nativesdk-shadow; however:
  Package nativesdk-shadow is not configured yet.

Setting up nativesdk-packagegroup-sdk-host (1.0-r12) ...
dpkg: nativesdk-qemu: dependency problems, but configuring anyway as you requested:
 nativesdk-qemu depends on nativesdk-libglib-2.0-0 (>= 2.64.5); however:
  Package nativesdk-libglib-2.0-0 is not configured yet.

Setting up nativesdk-qemu (5.1.0-r0) ...
dpkg: nativesdk-shared-mime-info: dependency problems, but configuring anyway as you requested:
 nativesdk-shared-mime-info depends on nativesdk-libglib-2.0-0 (>= 2.64.5); however:
  Package nativesdk-libglib-2.0-0 is not configured yet.

Setting up nativesdk-shared-mime-info (2.0-r0) ...
Errors were encountered while processing:
 nativesdk-shadow
 nativesdk-libglib-2.0-0
W: No sandbox user '_apt' on the system, can not drop privileges
W: chown to root:adm of file build/tmp/work/bytedevkit_am335x-poky-linux-gnueabi/bytesatwork-minimal-image/1.0-r0/recipe-sysroot-native/var/log/apt/term.log failed - OpenLog (1: Operation not permitted)
E: Sub-process dpkg returned an error code (1)

ERROR: Logfile of failure stored in: build/tmp/work/bytedevkit_am335x-poky-linux-gnueabi/bytesatwork-minimal-image/1.0-r0/temp/log.do_populate_sdk.42025
ERROR: Task (sources/meta-bytesatwork/recipes-core/images/bytesatwork-minimal-image.bb:do_populate_sdk) failed with exit code '1'